### ISSUE TITLE
Insufficient precision in Volume attribute

### ISSUE THREAD

**Issue by joaomlneto** [autonomouslogic/eve-ref#386] opened 2023-12-08 18:25 UTC
The display value of a type's Volume attribute is truncated to two decimal places, but its real value may have more.

An example is Null L: Its volume (attribute 161) is 0.025, but is displayed in EveRef as 0.02.
- https://everef.net/type/12787 
- https://esi.evetech.net/latest/universe/types/12787

This _may_ extend to other attributes

**Comment by kennethjor** [comment] 2023-12-08 18:51
Duplicate of https://github.com/autonomouslogic/eve-ref/issues/388

**Closed by kennethjor** 2023-12-08 18:51 UTC
